### ISSUE TITLE
Changing source path for forked copy

### ISSUE THREAD

**Issue by omnignorant** [stevenmaguire/bsfstemscholars#1]
Hey @stevenmaguire I forked a copy into the [hackshop repo](https://github.com/hackshop/bsfstemscholars) but the path structure must not be working because I'm just getting un-styled html for the [index page](http://hackshop.github.io/bsfstemscholars/) and all of the links push up a level to http://hackshop.github.io/ as the base url. I tried adjusting that in a bunch of different ways in the `_config.yml` file, including changing `baseurl`, adding a `source`, etc. What am I doing wrong here? I know there are some funky issues with Github pages and urls/paths, but this should be pretty straightforward and similar to what I've done with my [other website](http://hackshop.github.io/hackshop) which is [hosted in the same repo](http://github.com/hackshop/hackshop).

**Comment by stevenmaguire** [comment]
Without a `CNAME` file your project will be built to and accessible at http://hackshop.github.io/bsfstemscholars/

If you'd like to continue to work like that for a bit, you will need to update `_config.yml` to match to following:

```yml
baseurl: "/bsfstemscholars"
url: "http://hackshop.github.io/"
```

I always work on these sites under the assumption that I will be in the root domain until a compelling case otherwise presents itself. So, you may uncover some legitimate pathing issues that need to be corrected in order to make sub-directory hosting work. 

I would recommend working from a subdomain. In order to accomplish this, you will need to setup a CNAME record on your favorite domain pointing to hackshop.github.io and [include a file called `CNAME` in the root of the forked project](https://help.github.com/articles/setting-up-your-pages-site-repository/#adding-your-custom-domain-to-a-cname-file).

Give that a shot and let me know how it goes!

**Comment by omnignorant** [comment]
OK, setting up a subdomain was easy: http://jekyll.bsfstemscholars.com/ so I'll just work like that for a bit, but I'm still curious where I would modify the code to work from a non-root path purely from a curiosity standpoint.

**Comment by stevenmaguire** [comment]
Great! You would make the config changes I mentioned above and ensure that all resource links are generated using the base_url. 

https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/

Give it a try!
